In [115]:
import pandas as pd
from balldontlie import BalldontlieAPI
import time
import math
import numpy as np

In [116]:
#enter key
my_key = ''

In [117]:
#dont need
col = ['id', 'date', 'season', 'status', 'period', 'time', 'postseason',
       'home_team_score', 'visitor_team_score', 'home_team_id',
       'visitor_team_id', 'home_team.id', 'home_team.conference',
       'home_team.division', 'home_team.city', 'home_team.name',
       'home_team.full_name', 'home_team.abbreviation', 'visitor_team.id',
       'visitor_team.conference', 'visitor_team.division', 'visitor_team.city',
       'visitor_team.name', 'visitor_team.full_name',
       'visitor_team.abbreviation']
data = pd.DataFrame(columns= col)

In [118]:
def season_data(key, year = [2022]):
    ''''
    Allows you to pull season data from ballislife, need to pass your key and the years you want.
    Each year takes about 7 minutes but you can speed things up if you have a better plan
    Default year is 2022
    '''
    api = BalldontlieAPI(api_key= key)
    cur = None
    all_data = []
    while True:
        new_games = api.nba.games.list(seasons= year, per_page=100, cursor=cur)
        new_row = [ng.model_dump() for ng in new_games.data]
        all_data.extend(new_row)
        cur = new_games.meta.next_cursor
        if cur is None:
            break
        time.sleep(31) 
    df = pd.json_normalize(all_data,sep='.')
    return df

In [119]:
df = pd.read_csv("nba_2008-2025.csv")
df

,season,date,regular,playoffs,away,home,score_away,score_home,q1_away,q2_away,...,ot_home,whos_favored,spread,total,moneyline_away,moneyline_home,h2_spread,h2_total,id_spread,id_total
0,2008,10/30/2007,True,False,por,sas,97,106,26,23,...,0,home,13.0,189.5,900.0,-1400.0,5.0,95.0,0.0,1
1,2008,10/30/2007,True,False,uta,gsw,117,96,28,34,...,0,home,1.0,212.0,100.0,-120.0,3.0,105.5,0.0,1
2,2008,10/30/2007,True,False,hou,lal,95,93,16,27,...,0,away,5.0,199.0,-230.0,190.0,3.0,99.0,0.0,0
3,2008,10/31/2007,True,False,phi,tor,97,106,22,28,...,0,home,6.5,191.0,255.0,-305.0,2.0,96.5,1.0,1
4,2008,10/31/2007,True,False,was,ind,110,119,23,22,...,16,away,1.5,203.5,-125.0,105.0,1.0,105.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23113,2025,6/11/2025,False,True,okc,ind,107,116,32,28,...,0,away,4.5,225.5,NaN,NaN,NaN,NaN,0.0,0
23114,2025,6/13/2025,False,True,okc,ind,111,104,34,23,...,0,away,6.5,227.5,NaN,NaN,NaN,NaN,1.0,0
23115,2025,6/16/2025,False,True,ind,okc,109,120,22,23,...,0,home,8.5,223.5,NaN,NaN,NaN,NaN,1.0,1
23116,2025,6/19/2025,False,True,okc,ind,91,108,25,17,...,0,away,5.5,222.5,NaN,NaN,NaN,NaN,0.0,0
23117,2025,6/22/2025,False,True,ind,okc,91,103,22,26,...,0,home,6.5,215.5,NaN,NaN,NaN,NaN,1.0,0

In [120]:
#df = season_data(my_key, [2021])

In [121]:
df.dtypes

season              int64
date               object
regular              bool
playoffs             bool
away               object
home               object
score_away          int64
score_home          int64
q1_away             int64
q2_away             int64
q3_away             int64
q4_away             int64
ot_away             int64
q1_home             int64
q2_home             int64
q3_home             int64
q4_home             int64
ot_home             int64
whos_favored       object
spread            float64
total             float64
moneyline_away    float64
moneyline_home    float64
h2_spread         float64
h2_total          float64
id_spread         float64
id_total            int64
dtype: object

In [122]:
df.describe()

,season,score_away,score_home,q1_away,q2_away,q3_away,q4_away,ot_away,q1_home,q2_home,...,q4_home,ot_home,spread,total,moneyline_away,moneyline_home,h2_spread,h2_total,id_spread,id_total
count,23118.000000,23118.000000,23118.000000,23118.000000,23118.000000,23118.000000,23118.000000,23118.000000,23118.000000,23118.000000,...,23118.000000,23118.000000,23115.000000,23118.000000,19820.000000,19820.000000,19822.000000,19817.000000,23115.000000,23118.000000
mean,2016.500389,103.933731,106.579894,26.009776,26.097327,25.743144,25.412233,0.671252,26.897353,26.760057,...,25.781166,0.710356,6.150422,210.181395,124.229263,-254.547780,3.576716,103.027330,0.521999,0.515789
std,5.212645,13.710616,13.567418,5.951920,5.901064,6.037957,5.984585,3.047784,5.975630,5.910055,...,5.891295,3.190743,3.683346,15.450553,430.106555,680.035795,2.579336,7.077542,0.527744,0.522527
min,2008.000000,54.000000,59.000000,7.000000,4.000000,5.000000,5.000000,0.000000,5.000000,5.000000,...,7.000000,0.000000,0.000000,170.000000,-9900.000000,-13000.000000,0.000000,84.000000,0.000000,0.000000
25%,2012.000000,94.000000,97.000000,22.000000,22.000000,22.000000,21.000000,0.000000,23.000000,23.000000,...,22.000000,0.000000,3.500000,197.500000,-140.000000,-340.000000,1.500000,97.500000,0.000000,0.000000
50%,2016.000000,104.000000,106.000000,26.000000,26.000000,26.000000,25.000000,0.000000,27.000000,27.000000,...,26.000000,0.000000,5.500000,210.000000,145.000000,-170.000000,3.000000,103.000000,1.000000,1.000000
75%,2021.000000,113.000000,116.000000,30.000000,30.000000,30.000000,29.000000,0.000000,31.000000,31.000000,...,30.000000,0.000000,8.500000,222.000000,280.000000,120.000000,5.000000,108.000000,1.000000,1.000000
max,2025.000000,176.000000,175.000000,55.000000,49.000000,52.000000,51.000000,44.000000,55.000000,51.000000,...,50.000000,41.000000,23.500000,262.500000,6500.000000,3000.000000,16.500000,125.000000,2.000000,2.000000

In [123]:
data = df[[	'season','date','away','home','score_away','score_home','moneyline_away','moneyline_home']]
data['home_win'] = (data['score_home'] > data['score_away']).astype(int)
data['date'] = pd.to_datetime(data.date)
data['away'] = [x.upper() for x in data.away]
data['home'] = [x.upper() for x in data.home]
data['score_home'] = data['score_home'].astype(int)
data['score_away'] = data['score_away'].astype(int)
data2022 = data[data['season'] == 2022]

C:\Users\JacobPolomsky\AppData\Local\Temp\ipykernel_3272\3898106702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['home_win'] = (data['score_home'] > data['score_away']).astype(int)
C:\Users\JacobPolomsky\AppData\Local\Temp\ipykernel_3272\3898106702.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['date'] = pd.to_datetime(data.date)
C:\Users\JacobPolomsky\AppData\Local\Temp\ipykernel_3272\3898106702.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['away'] = [x.upper() for x in data.away]
C:\Users\JacobPolomsky\AppData\Local\Temp\ipykernel_3272\3898106702.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['home'] = [x.upper() for x in data.home]
C:\Users\JacobPolomsky\AppData\Local\Temp\ipykernel_3272\3898106702.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['score_home'] = data['score_home'].astype(int)
C:\Users\JacobPolomsky\AppData\Local\Temp\ipykernel_3272\3898106702.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['score_away'] = data['score_away'].astype(int)

In [124]:
data2022.head()

,season,date,away,home,score_away,score_home,moneyline_away,moneyline_home,home_win
17835,2022,2021-10-19,BKN,MIL,104,127,105.0,-125.0,1
17836,2022,2021-10-19,GSW,LAL,121,114,140.0,-160.0,0
17837,2022,2021-10-20,IND,CHA,122,123,-125.0,105.0,1
17838,2022,2021-10-20,CHI,DET,94,88,-220.0,190.0,0
17839,2022,2021-10-20,WAS,TOR,98,83,120.0,-140.0,0

In [125]:
data2022.dtypes

season                     int64
date              datetime64[ns]
away                      object
home                      object
score_away                 int64
score_home                 int64
moneyline_away           float64
moneyline_home           float64
home_win                   int64
dtype: object

In [126]:
# Define starting Elo for all teams, Home field advantage, and K. 
all_elo = {}
r0 = 1500
K = 20
H = 60
for x in data.home.unique():
    all_elo[x] = r0
all_elo

{'SAS': 1500,
 'GSW': 1500,
 'LAL': 1500,
 'TOR': 1500,
 'IND': 1500,
 'ORL': 1500,
 'BKN': 1500,
 'CLE': 1500,
 'MEM': 1500,
 'NOP': 1500,
 'DEN': 1500,
 'MIA': 1500,
 'UTA': 1500,
 'OKC': 1500,
 'CHA': 1500,
 'ATL': 1500,
 'BOS': 1500,
 'MIN': 1500,
 'CHI': 1500,
 'PHX': 1500,
 'LAC': 1500,
 'PHI': 1500,
 'WAS': 1500,
 'MIL': 1500,
 'HOU': 1500,
 'DAL': 1500,
 'NYK': 1500,
 'DET': 1500,
 'SAC': 1500,
 'POR': 1500}

In [127]:
def win_prob(home_rating, away_rating):
    ''''
    Probability of Winning for the home team when you provide the ratings and homefield advantage
    '''
    p_home = 1 / (1 + 10 ** -((home_rating + H - away_rating)/400))
    return p_home

In [128]:
#testing win_prob on elo
print(win_prob(1500, 1500))
print(win_prob(1600, 1500))    
print(win_prob(1400, 1600))

0.5854986786718095
0.7152527510491987
0.308763847585237

In [129]:
def update_rating(home, away, home_win):
    ''''
    Update Rating of the Winner
    '''
    #gets the ratings
    home_rating = all_elo[home]
    away_rating = all_elo[away]
    #gets the probabilty of home team winning
    p_home = win_prob(home_rating, away_rating)
    #updates the new rating
    home_rating += K * (home_win - p_home)
    away_rating += K * ((1 - home_win) - (1 - p_home))
    #makes the new rating permenate
    all_elo[home] = home_rating
    all_elo[away] = away_rating

In [130]:
update_rating("LAL", "BOS", 1)
print(all_elo["LAL"], all_elo["BOS"])

1508.2900264265638 1491.7099735734362

In [131]:
#save predictions
pred = []
for g in data2022.itertuples():
    # our predictions
    home_rat = all_elo[g.home]
    away_rat = all_elo[g.away]
    home_pred = win_prob(home_rat, away_rat)
    #saving our predictions
    pred.append(home_pred)
    #updating rating
    update_rating(g.home, g.away, g.home_win)

pred

[0.5854986786718095,
 0.5970309012863722,
 0.5854986786718095,
 0.5854986786718095,
 0.5854986786718095,
 0.5970309012863722,
 0.5854986786718095,
 0.5854986786718095,
 0.5854986786718095,
 0.5854986786718095,
 0.5854986786718095,
 0.5854986786718095,
 0.5854986786718095,
 0.5854986786718095,
 0.5738719832384975,
 0.602076200218781,
 0.5624898056656714,
 0.562163039175688,
 0.6131368201531431,
 0.5790027755288308,
 0.6131368201531431,
 0.5854986786718095,
 0.617796002006283,
 0.5902682850530583,
 0.596711436382997,
 0.5902682850530583,
 0.5461740382402405,
 0.5508405569605628,
 0.596850962294129,
 0.6235209303793404,
 0.6281309010977595,
 0.5859567290217306,
 0.5687342580649433,
 0.562632747599421,
 0.5636069740284264,
 0.6385371502999754,
 0.6239064876538155,
 0.5629460774242784,
 0.5573194645626705,
 0.5357333792103286,
 0.5593973191342523,
 0.64832008059767,
 0.5942835696033811,
 0.5303877500850226,
 0.6108963123923276,
 0.5477097996523613,
 0.6436421289011494,
 0.6271856214198398,
 0.562805599913122,
 0.5796645322050795,
 0.5016053888819174,
 0.6078327681562307,
 0.5780415472370222,
 0.603170554398055,
 0.5391751153980366,
 0.5772226690935706,
 0.5792788840607703,
 0.5558819037996805,
 0.5673894136752582,
 0.5242553379222951,
 0.6127650585426256,
 0.5894616396427682,
 0.554347223892442,
 0.5678587122642416,
 0.6256600228344534,
 0.5905690455423637,
 0.6164822539513654,
 0.5167544498262941,
 0.6329730566056369,
 0.6397112273493786,
 0.6013395420136239,
 0.5722743947464684,
 0.6088247758590032,
 0.5492362987169123,
 0.6116459768788068,
 0.5581542622253141,
 0.5605788929755096,
 0.6450501077101927,
 0.5844140137671656,
 0.495124508432925,
 0.5456608969282614,
 0.5853053841862665,
 0.5668083645814692,
 0.6413164367339186,
 0.5663607881520942,
 0.6618235668583794,
 0.5951609952454403,
 0.5504187489642112,
 0.5833481220993708,
 0.6065851719958115,
 0.5400504874944467,
 0.6187605795111277,
 0.6336635472041006,
 0.6297540221954055,
 0.6146334196166724,
 0.5463722263240448,
 0.6301282597436292,
 0.535334424992842,
 0.5076769395080752,
 0.5610673743428111,
 0.6469984955972845,
 0.5932001954547946,
 0.5565712876681163,
 0.5562421205505635,
 0.6364833651332997,
 0.6331630282005055,
 0.6530148837203319,
 0.6117475190949573,
 0.5883922888247242,
 0.6001081718797803,
 0.5600090999453812,
 0.4987258798135783,
 0.5781123794739595,
 0.5857838772742626,
 0.6019020853732542,
 0.5373852468662363,
 0.6522792642331988,
 0.6127348467553354,
 0.47204125282509196,
 0.5211591748767016,
 0.6782168810997801,
 0.6414709625872227,
 0.6687676659731066,
 0.5809362162764012,
 0.48792886376472083,
 0.5797133551581868,
 0.562098080113478,
 0.6038209717593772,
 0.5682718276680037,
 0.7188720149913932,
 0.5788999582058495,
 0.5963466177839336,
 0.6599599989620085,
 0.5550987123007296,
 0.5729553297134594,
 0.6181805773843004,
 0.6011172434874564,
 0.5632085286343103,
 0.5761198763817615,
 0.6475409710104146,
 0.5822687022670912,
 0.4402779714521051,
 0.6366972623123347,
 0.5799277502779513,
 0.7237438050997483,
 0.5893687586493717,
 0.6418420163299852,
 0.5690071328105641,
 0.6460282280456692,
 0.7052020113935,
 0.5350050447534979,
 0.6786342246730855,
 0.567325067238263,
 0.5934788187503278,
 0.6702681396704853,
 0.6667116757129202,
 0.6019385198551134,
 0.5970901987158702,
 0.48855659243197247,
 0.5587008106203974,
 0.6322868299203203,
 0.5849965319449215,
 0.6343656940891964,
 0.5138890661956892,
 0.5865679002488527,
 0.5554508399159221,
 0.6297566931244628,
 0.6408730012967653,
 0.7158283222513843,
 0.541040309333351,
 0.6299777309820099,
 0.6830204762907113,
 0.572960300400809,
 0.5589886220724033,
 0.6914380797058708,
 0.5714209735102566,
 0.501333851471365,
 0.41642589036571703,
 0.5513715124340649,
 0.6003390449694367,
 0.5163650298652771,
 0.6602148520948631,
 0.6206655464031569,
 0.6658925629941324,
 0.6029743774328535,
 0.4507551964243852,
 0.5408158402727498,
 0.4637049037130146,
 0.676222364336156,
 0.6266550805380353,
 0.6650532291499786,
 0.6353036436871835,
 0.5392097862106802,
 0.48662100231891425,
 0.40446406395825174,
 0.5171810974157109,
 0.6403302183268804,
 0.5861017315038706,
 0.7513223015449567,
 0.6465387820756064,
 0.5642155295380356,
 0.6011406747543018,
 0.6312700150006234,
 0.6891963237642408,
 0.5759218513760723,
 0.45930146957734946,
 0.5228235423475756,
 0.5713303195046395,
 0.5335155677273732,
 0.5740305418464882,
 0.6015917020456724,
 0.6720930778055909,
 0.5250652613604253,
 0.5248221504814868,
 0.7444170297596938,
 0.69229016861334,
 0.6065628712950956,
 0.5449443653627353,
 0.5719896065051039,
 0.6868495784630942,
 0.5433770259253998,
 0.6080973781672644,
 0.4986159184999329,
 0.5831302655207544,
 0.5083352460369266,
 0.5998777530706788,
 0.5317985285769126,
 0.6299236400980573,
 0.6396823513128541,
 0.6497290797747473,
 0.3981044257320694,
 0.601641628209902,
 0.7211934474057509,
 0.6048912179208825,
 0.43047694407594966,
 0.5487733397506303,
 0.6293806111341228,
 0.5745252127103295,
 0.7226530165440671,
 0.650831391664761,
 0.5644275548686278,
 0.5269905211583419,
 0.6320502107193725,
 0.5417418614208469,
 0.6702700628257701,
 0.48066700912610916,
 0.5746967009764119,
 0.5582646403140895,
 0.5351530137516614,
 0.6728550967310747,
 0.6546175028152834,
 0.716876294512433,
 0.519158896922193,
 0.6220539870431502,
 0.6298644513092939,
 0.7468676940875414,
 0.6990691390950987,
 0.686827688113637,
 0.49523764280014776,
 0.38997226071538404,
 0.6575293987288914,
 0.5109149422680105,
 0.42680404052012216,
 0.5949742042912751,
 0.6009421622942203,
 0.5831785559836853,
 0.5957379732088244,
 0.46002015934209967,
 0.43411540000339904,
 0.5190157598316525,
 0.7045765544794458,
 0.48403510266068406,
 0.3513341637343768,
 0.4906785843989218,
 0.6100510725660625,
 0.3991366743436965,
 0.48253178929153434,
 0.4713614827287646,
 0.6971473695542593,
 0.6967574717555904,
 0.6463550968939816,
 0.4558684932928649,
 0.41889692670169404,
 0.5502992793981359,
 0.5582946868238988,
 0.48008548350209884,
 0.46347990412783596,
 0.7421396949470365,
 0.5443322620161335,
 0.7086374510956245,
 0.6450483836839165,
 0.608763234659577,
 0.626883787232894,
 0.5454497502503362,
 0.36765986262788647,
 0.5861678147221884,
 0.6911206246393787,
 0.5802410322798899,
 0.7081127073923943,
 0.44290600764355864,
 0.5199389863675709,
 0.6077141873260482,
 0.5709660248544617,
 0.6767572055588055,
 0.7043005988724907,
 0.6824924228396458,
 0.5401901508917728,
 0.6211082483586798,
 0.579441394152488,
 0.6144003418378121,
 0.4295598436582128,
 0.6224998116247056,
 0.6864084656112489,
 0.570850485274421,
 0.6625490162146763,
 0.5398108730543497,
 0.5823882048563256,
 0.702612511033779,
 0.617030020727483,
 0.5213008798120439,
 0.4460106440413434,
 0.5988192780676688,
 0.6305118975064921,
 0.4910120524373523,
 0.6043903380203411,
 0.6068376751547873,
 0.6431196526564501,
 0.5312893740371133,
 0.4632301196796873,
 0.6921002622701473,
 0.8367460273766733,
 0.660710719052158,
 0.4851373202606106,
 0.6121047766125337,
 0.6291651486865617,
 0.679723231070074,
 0.6125977577546211,
 0.6984211741488566,
 0.6128940204006008,
 0.5605111005629378,
 0.619161255241783,
 0.5951816272898124,
 0.6243410302480185,
 0.588336601958584,
 0.5794414960251412,
 0.77964622915615,
 0.554908781265253,
 0.5445429748176557,
 0.5680118664137653,
 0.5118340314918638,
 0.5739745963767013,
 0.5766963001491864,
 0.6217891496736138,
 0.5650916474401152,
 0.48610761605081165,
 0.6043336773052769,
 0.6750653941032843,
 0.5790562879593317,
 0.6222501130631105,
 0.7640117203739467,
 0.5855770003723734,
 0.8187949526634303,
 0.47453841920517215,
 0.5723850408034088,
 0.5356644587134745,
 0.5399965657406607,
 0.5063249755860394,
 0.4118825108124954,
 0.5875816479177134,
 0.6697019695192789,
 0.5314152534467936,
 0.3987035245910597,
 0.48134959089697554,
 0.6520189271369715,
 0.506132332269671,
 0.6777543915258938,
 0.7607999395931049,
 0.5531249604988685,
 0.5324633910584557,
 0.6130858582108764,
 0.5269299246105984,
 0.6320971462882228,
 0.5509241790835141,
 0.5110371806167934,
 0.5725727050753308,
 0.5147539856051733,
 0.4570511309437772,
 0.5125778660529665,
 0.648253022297956,
 0.73864672590801,
 0.7233831506297477,
 0.49838037666670154,
 0.6857806128484242,
 0.5392258981673678,
 0.6770827431935456,
 0.4525759891839899,
 0.5539769510236253,
 0.46745018761735546,
 0.30437839939113753,
 0.6213803902902598,
 0.5039890202909119,
 0.5812123007694372,
 0.7296178052387225,
 0.591586336787379,
 0.40937350794337096,
 0.6154936568351611,
 0.6663940200275018,
 0.48959507360952786,
 0.5855155298316924,
 0.5559462506586658,
 0.5790913859819508,
 0.40718857011703546,
 0.38006417668481574,
 0.7053611261726395,
 0.34987017375344076,
 0.4312908177762826,
 0.7086037908750747,
 0.5754843148149098,
 0.5841289596157908,
 0.575331644149431,
 0.6987963575199287,
 0.527303848764248,
 0.6324562516989752,
 0.5200126257478673,
 0.6809694599682312,
 0.44924422272068437,
 0.7130273709822142,
 0.6870580332105329,
 0.5751470615590921,
 0.7554059019906917,
 0.34899702013517403,
 0.5847987485784465,
 0.43097421416311604,
 0.5476901937274555,
 0.759217533773585,
 0.46725462164394654,
 0.46333385047279896,
 0.4060706940626099,
 0.47349046740543016,
 0.8399442372598507,
 0.38388278071960036,
 0.4363965293638699,
 0.6291250565960856,
 0.5774392365517742,
 0.7095524450293317,
 0.6462670936277454,
 0.561141948844034,
 0.7290783120045946,
 0.31197664985481544,
 0.5947310538468815,
 0.7418496982294588,
 0.5904196718163417,
 0.7441909331796233,
 0.7279989682189941,
 0.6710353391809167,
 0.7720970872779546,
 0.6365270631376954,
 0.7118637765154193,
 0.671973090028475,
 0.5688871914930076,
 0.5532721700181884,
 0.39359025570096284,
 0.7196690660920335,
 0.48378292515420906,
 0.7107707028612084,
 0.47382067126563765,
 0.5446207151777105,
 0.6459849853918405,
 0.6217590863601,
 0.5004502342820993,
 0.8012595350272049,
 0.5411314579908952,
 0.5118641071326989,
 0.6840971573482547,
 0.5920728913884773,
 0.8175928748905966,
 0.7042393956707395,
 0.6102487434555388,
 0.5453256625054017,
 0.6507610326628154,
 0.6164126428061744,
 0.44718099951588947,
 0.7102482002217544,
 0.7780053230551648,
 0.5937731327401217,
 0.667303162648279,
 0.47792373855204745,
 0.5462865814732675,
 0.7512195392981529,
 0.7079074953105596,
 0.5984675684481587,
 0.6883009204187328,
 0.4504573625133756,
 0.5739524150578583,
 0.45337150317201474,
 0.7188250076131212,
 0.5494278420196258,
 0.44174222978567895,
 0.3347987128667242,
 0.5492600602667358,
 0.6553825397060898,
 0.6326380350771412,
 0.5169992701378696,
 0.43366076213314,
 0.7564565165770191,
 0.5700051387827544,
 0.402651891700771,
 0.5169435977256988,
 0.6059660177713436,
 0.6715945825879394,
 0.7297432062455185,
 0.799899850171167,
 0.3693486382905525,
 0.5255845522826116,
 0.6767548535225908,
 0.49721649245273025,
 0.31785424124431466,
 0.37998551925650154,
 0.4003001231032323,
 0.5527197806230135,
 0.38211512837302386,
 0.6927086913961409,
 0.571783592379879,
 0.5131288220199854,
 0.6785819812049255,
 0.7305209446244117,
 0.6428398306517784,
 0.7221458527173388,
 0.45408326393590115,
 0.394414952634454,
 0.7167112331429656,
 0.42858479712786685,
 0.56348791322134,
 0.6004913384750005,
 0.6939369189846107,
 0.7403192351426673,
 0.4147869754753952,
 0.5227178355845181,
 0.45938399305093286,
 0.5857175355553693,
 0.7633786258123516,
 0.5536662506324598,
 0.5967364067401694,
 0.8388980027441176,
 0.8472117310870562,
 0.398757489355174,
 0.5519505693460045,
 0.5150856160402433,
 0.6922118021557935,
 0.6140135464223846,
 0.628438911041832,
 0.5346417135601214,
 0.6241915884712465,
 0.3526549681532285,
 0.6329899082422344,
 0.3294736236727542,
 0.7542192264823339,
 0.7255535064555861,
 0.6401493454678259,
 0.4002053809290884,
 0.41162622742354465,
 0.654862150918402,
 0.667259537060627,
 0.5613188697055989,
 0.42781325370336964,
 0.45968491236126446,
 0.5745719839980198,
 0.3355158480764192,
 0.8302923023345079,
 0.7659244729926994,
 0.6935086669018901,
 0.6034008160146311,
 0.4486950629588663,
 0.4221808726678246,
 0.4927064534249209,
 0.7367713802110909,
 0.6766430263264919,
 0.4465369973879178,
 0.61445474169171,
 0.43208793271709967,
 0.3387579659122285,
 0.5960675177897521,
 0.5113459003495532,
 0.5725560529085989,
 0.6889556556314141,
 0.5850059479661631,
 0.3947074468297698,
 0.6731351344798987,
 0.43572402739417543,
 0.45129479175491943,
 0.4698640285068503,
 0.7007921675082024,
 0.6920553381730398,
 0.5676026468978853,
 0.45975339435267426,
 0.28790757201399764,
 0.5393952135640261,
 0.6114131063986333,
 0.6480008197036445,
 0.43573035801059923,
 0.3489955967591832,
 0.39989218400863336,
 0.6910227373080046,
 0.46379440613445294,
 0.5612130215476837,
 0.5052875224562294,
 0.5231543875941114,
 0.829639712393313,
 0.633597029201675,
 0.7763983574882565,
 0.4998654017367958,
 0.5057517484102992,
 0.43204280966842595,
 0.675565884341524,
 0.6370533847236901,
 0.4670348289744925,
 0.6634052202686687,
 0.48881017109791536,
 0.7267378691247014,
 0.555101469037298,
 0.7757990432883902,
 0.6822953754993627,
 0.8236123602633735,
 0.3824474219581688,
 0.2998772043972153,
 0.6542023643573074,
 0.5697428057779773,
 0.7434119454595562,
 0.4251764960322984,
 0.6244897732953032,
 0.699762746460161,
 0.6421252375443602,
 0.6752234863340498,
 0.6775173310487363,
 0.5191375796484486,
 0.38870191966917683,
 0.6178226383430596,
 0.4651078216154501,
 0.514178303854279,
 0.6295635437408851,
 0.8111960663472573,
 0.6445375976049391,
 0.41974330079560074,
 0.5351866419306267,
 0.26117778661430785,
 0.6364520373330969,
 0.5553833564102062,
 0.46395719612990854,
 0.6067908649415127,
 0.633818336951905,
 0.6572207660621956,
 0.4368114182308025,
 0.44432073464511934,
 0.6464236020551026,
 0.3061351988096457,
 0.7568156993882517,
 0.45242206406336855,
 0.5648138468220812,
 0.8275371011375566,
 0.5218026341977985,
 0.8354440051884094,
 0.5508534061409562,
 0.7404795617202601,
 0.4840404744876491,
 0.5682912289571895,
 0.47016810848711976,
 0.6330658883613092,
 0.6206095521465866,
 0.7795392394967459,
 0.6317585029259862,
 0.6395917498857241,
 0.6926357539064896,
 0.6151769353841819,
 0.4632323574360552,
 0.8013662475212425,
 0.7696208486616264,
 0.38608295488075284,
 0.710490597563209,
 0.4092499732430223,
 0.6552176006155455,
 0.5511868762229869,
 0.5447273392941624,
 0.4240439870684239,
 0.7673783196498191,
 0.4741111730665358,
 0.7913215016718356,
 0.7903136227932261,
 0.7631251181637265,
 0.8311520260204767,
 0.5680357340931366,
 0.5676095713622885,
 0.6647952340289243,
 0.2699553613888012,
 0.6999310997572004,
 0.693874232067086,
 0.4157255899768181,
 0.5021595163341497,
 0.7373824865375054,
 0.5119254298421726,
 0.643836059272756,
 0.7034984370394815,
 0.637369895525606,
 0.7334020251445863,
 0.36525737842675904,
 0.5723618952709638,
 0.40080730329830067,
 0.5429497607569973,
 0.6833052595444049,
 0.7129039634881387,
 0.5721978487086681,
 0.6385345103479626,
 0.5250658908889051,
 0.6886722732476854,
 0.3827695816726036,
 0.4400049714880168,
 0.6132697835495825,
 0.701463791092595,
 0.35223151485464743,
 0.7200034434240171,
 0.4055088503719937,
 0.4597670245901958,
 0.6014740024499748,
 0.633648877159732,
 0.6828159640449056,
 0.6884680562558022,
 0.6579102015917363,
 0.5207073895672719,
 0.5642428932884388,
 0.7027718030840956,
 0.5069425541623822,
 0.6879366049601097,
 0.5337129046147212,
 0.39569541796256386,
 0.7689668791983936,
 0.6908950701970812,
 0.49430589057797325,
 0.5392964680614974,
 0.75277360495333,
 0.7998896375339833,
 0.7802435076379328,
 0.6883721107013577,
 0.700966801999994,
 0.6146128835647766,
 0.6641812948253272,
 0.6930508614411461,
 0.2944530186728131,
 0.5925126249351976,
 0.28011464874155395,
 0.5790660031484123,
 0.8474022654481467,
 0.7323064079105068,
 0.5249678509452557,
 0.4778322678068816,
 0.6847880189252098,
 0.49009425483960284,
 0.2754112721963967,
 0.45849593710149866,
 0.5608542356688633,
 0.4950981316152375,
 0.7064726292898674,
 0.5391846378858578,
 0.8135930846910454,
 0.3223674862810253,
 0.7804494435021307,
 0.544887603030403,
 0.7614666499852734,
 0.6917616418649056,
 0.5654422950655805,
 0.38582805013683996,
 0.3240990846036973,
 0.790827958150266,
 0.5348528010739633,
 0.3932640059685345,
 0.6137740403686112,
 0.35791122489984406,
 0.3229737067183732,
 0.6016684075481287,
 0.8486442035658242,
 0.5664815071175787,
 0.4065006080663152,
 0.5335131288630506,
 0.36136978603197534,
 0.4031335173564138,
 0.6455760493025119,
 0.6157385545970415,
 0.5413436958312623,
 0.6146947442764278,
 0.6952731801055526,
 0.6449640228853591,
 0.2541349139609904,
 0.29327555530833144,
 0.5135051133137073,
 0.6003106658023295,
 0.5537982290587928,
 0.417709155005449,
 0.8020622220159054,
 0.5822915770220037,
 0.6294946640631164,
 0.7775821490119635,
 0.6465932543569776,
 0.34651401856809133,
 0.47106721680957925,
 0.5034051607195722,
 0.5028895070682092,
 0.4122949011937595,
 0.3997945697204313,
 0.27089343307963626,
 0.6916781852506605,
 0.4243181798319686,
 0.5103529788611422,
 0.6987621958392829,
 0.7140433253616368,
 0.7524251903496704,
 0.8150936791688742,
 0.7027378237689801,
 0.4608122822850143,
 0.6716450123260719,
 0.37387341836332066,
 0.7661717186949292,
 0.5207539066604109,
 0.34226428549972326,
 0.3539496416236527,
 0.4979663487810071,
 0.44004208665288724,
 0.22688047606308712,
 0.5375225816713762,
 0.45002121480870994,
 0.3078445247338307,
 0.6852142082471531,
 0.736334209308975,
 0.8076955624687947,
 0.7925811413894766,
 0.3376752619128781,
 0.3953498142101281,
 0.5996283738388973,
 0.6871839030261279,
 0.5944497336539564,
 0.7984617008997512,
 0.5316441499708194,
 0.38640044321617206,
 0.6399611670729906,
 0.6529107677150485,
 0.5581472696978066,
 0.6542639777741673,
 0.7902818325249501,
 0.7408203914123144,
 0.7006345230326064,
 0.7737911941906093,
 0.9053593107994351,
 0.680787642183018,
 0.3899296764547324,
 0.7149095479289943,
 0.6716279823842762,
 0.6491660823466803,
 0.7623127267117521,
 0.43529928819753066,
 0.7266033243701331,
 0.8007824495494099,
 0.8017979912112247,
 0.4052686437896394,
 0.6004702068783856,
 0.6479124411858893,
 0.4471586044507727,
 0.7858178575668763,
 0.3580110969700536,
 0.665474654457177,
 0.8152658002078144,
 0.39804041758891506,
 0.5322923352083799,
 0.4975946634049835,
 0.8510133164183918,
 0.7770014211366615,
 0.514178753517704,
 0.8196217960154925,
 0.5703417558388023,
 0.9078518773811645,
 0.6601793120640859,
 0.4386411909475958,
 0.4319098490320854,
 0.6470132080158937,
 0.45164328340665694,
 0.5775822131304248,
 0.7533478167226494,
 0.29047524959725113,
 0.4536346075824272,
 0.6796562225009304,
 0.1822812294672703,
 0.4543661934939486,
 0.3959160810855494,
 0.36242024866497047,
 0.5749340789378069,
 0.603133519588288,
 0.43743703588473676,
 0.5754976122517572,
 0.34723825739060477,
 0.5462770498198221,
 0.5486042576830308,
 0.8555917134249519,
 0.5316631046129968,
 0.3044106585016335,
 0.4917352080872111,
 0.7506499793689546,
 0.7330482826390443,
 0.5276196280716879,
 0.7009277690709474,
 0.7923420289487053,
 0.34496958172518005,
 0.7568736801203696,
 0.3168920630098515,
 0.7363212269654259,
 0.3560124742826306,
 0.6358070156120225,
 0.40925855032027963,
 0.5537728477520412,
 0.5359430987851436,
 0.6144516074705895,
 0.4766695004285684,
 0.6363164178738382,
 0.7861307744114218,
 0.678137725803366,
 0.5854433768040511,
 0.6626806141821867,
 0.663642344921145,
 0.709698985795154,
 0.33744780633848187,
 0.5317116563750117,
 0.3979600164465943,
 0.7017820633241161,
 0.5623915784065378,
 0.8039918890294775,
 0.48321143069721806,
 0.6953274798348251,
 0.2699864426444878,
 0.8178223711963607,
 0.8450660196295627,
 0.49680701106899333,
 0.3827301933048687,
 0.8143014294453567,
 0.4940199937426306,
 0.6647112524675973,
 0.5937995030472082,
 0.7059476380808604,
 0.6735014494724743,
 0.5662885384333791,
 0.4876590787632969,
 0.584860834095264,
 0.8078425103044836,
 0.4699044536610078,
 0.3592547623778347,
 0.8447458378140907,
 0.8736637012340674,

In [132]:
data2022["h_prob"] = pred
data2022["a_prob"] = 1 - data2022["h_prob"]

C:\Users\JacobPolomsky\AppData\Local\Temp\ipykernel_3272\1797557186.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2022["h_prob"] = pred
C:\Users\JacobPolomsky\AppData\Local\Temp\ipykernel_3272\1797557186.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2022["a_prob"] = 1 - data2022["h_prob"]

In [133]:
data2022.head(10)

,season,date,away,home,score_away,score_home,moneyline_away,moneyline_home,home_win,h_prob,a_prob
17835,2022,2021-10-19,BKN,MIL,104,127,105.0,-125.0,1,0.585499,0.414501
17836,2022,2021-10-19,GSW,LAL,121,114,140.0,-160.0,0,0.597031,0.402969
17837,2022,2021-10-20,IND,CHA,122,123,-125.0,105.0,1,0.585499,0.414501
17838,2022,2021-10-20,CHI,DET,94,88,-220.0,190.0,0,0.585499,0.414501
17839,2022,2021-10-20,WAS,TOR,98,83,120.0,-140.0,0,0.585499,0.414501
17840,2022,2021-10-20,BOS,NYK,134,138,120.0,-140.0,1,0.597031,0.402969
17841,2022,2021-10-20,CLE,MEM,121,132,240.0,-280.0,1,0.585499,0.414501
17842,2022,2021-10-20,PHI,NOP,117,97,-170.0,150.0,0,0.585499,0.414501
17843,2022,2021-10-20,HOU,MIN,106,124,220.0,-260.0,1,0.585499,0.414501
17844,2022,2021-10-20,ORL,SAS,97,123,225.0,-265.0,1,0.585499,0.414501

In [134]:
def brier_baseline(data):
    baseline = data.home_win.mean()
    brier = np.mean((baseline - data.home_win) ** 2)
    return brier

In [135]:
def brier_model(data):
    prediction = data.h_prob
    brier_score = np.mean((prediction - data.home_win) ** 2)
    return brier_score

In [136]:
print(brier_baseline(data2022))
print(brier_model(data2022))

0.247696290240292
0.22737017448037916

### Betting

In [137]:
data2022

,season,date,away,home,score_away,score_home,moneyline_away,moneyline_home,home_win,h_prob,a_prob
17835,2022,2021-10-19,BKN,MIL,104,127,105.0,-125.0,1,0.585499,0.414501
17836,2022,2021-10-19,GSW,LAL,121,114,140.0,-160.0,0,0.597031,0.402969
17837,2022,2021-10-20,IND,CHA,122,123,-125.0,105.0,1,0.585499,0.414501
17838,2022,2021-10-20,CHI,DET,94,88,-220.0,190.0,0,0.585499,0.414501
17839,2022,2021-10-20,WAS,TOR,98,83,120.0,-140.0,0,0.585499,0.414501
...,...,...,...,...,...,...,...,...,...,...,...
19153,2022,2022-06-05,BOS,GSW,88,107,175.0,-200.0,1,0.521126,0.478874
19154,2022,2022-06-08,GSW,BOS,100,116,135.0,-155.0,1,0.621509,0.378491
19155,2022,2022-06-10,GSW,BOS,107,97,145.0,-165.0,0,0.641782,0.358218
19156,2022,2022-06-13,BOS,GSW,94,104,145.0,-165.0,1,0.563516,0.436484
19157,2022,2022-06-16,GSW,BOS,103,90,155.0,-175.0,0,0.582934,0.417066

In [138]:
def price_to_prob(price):
    
    if price > 0:
        p_hat = 100 / (price + 100)
    else:
        p_hat = -price / (-price + 100)
    return p_hat

In [139]:
def implied_prob(ph_home, ph_away):
    s = ph_home + ph_away
    p_home = ph_home / s
    p_away = ph_away / s
    return [p_home, p_away]

In [140]:
def american_to_decimal(price):
    if price > 0:
        sigma = 1 + (price / 100) 
    else:
        sigma = 1 + (100/ - price)
    return sigma

In [141]:
def expected_value(prob_model, price):
    sigma = american_to_decimal(price)
    beta = sigma - 1
    return prob_model * beta - (1 - prob_model)

In [142]:
def Kelly_fraction(prob_model, price):
    sigma = american_to_decimal(price)
    beta = sigma - 1
    f = expected_value(prob_model, price) / beta
    return min(max(f,0),0.05)

In [143]:
vegas = pd.DataFrame()

In [144]:
vegas['home_odds'] = [price_to_prob(p) for p in data2022['moneyline_home']]
vegas['away_odds'] = [price_to_prob(p) for p in data2022['moneyline_away']]

In [145]:
vegas

      home_odds  away_odds
0      0.555556   0.487805
1      0.615385   0.416667
2      0.487805   0.555556
3      0.344828   0.687500
4      0.583333   0.454545
...         ...        ...
1318   0.666667   0.363636
1319   0.607843   0.425532
1320   0.622642   0.408163
1321   0.622642   0.408163
1322   0.636364   0.392157

[1323 rows x 2 columns]

In [146]:
ph = [implied_prob(hp, ap) for hp, ap in vegas.iloc]

In [147]:
pha = []
phh = []
for hp, ap in ph:
    phh.append(hp)
    pha.append(ap)
vegas['implied_home_prob'] = phh
vegas['implied_away_prob'] = pha

In [148]:
data2022 = data2022.reset_index()
data2022['vegas_home_prob'] = vegas['implied_home_prob']
data2022['vegas_away_prob'] = vegas['implied_away_prob']

In [149]:
data2022

,index,season,date,away,home,score_away,score_home,moneyline_away,moneyline_home,home_win,h_prob,a_prob,vegas_home_prob,vegas_away_prob
0,17835,2022,2021-10-19,BKN,MIL,104,127,105.0,-125.0,1,0.585499,0.414501,0.532468,0.467532
1,17836,2022,2021-10-19,GSW,LAL,121,114,140.0,-160.0,0,0.597031,0.402969,0.596273,0.403727
2,17837,2022,2021-10-20,IND,CHA,122,123,-125.0,105.0,1,0.585499,0.414501,0.467532,0.532468
3,17838,2022,2021-10-20,CHI,DET,94,88,-220.0,190.0,0,0.585499,0.414501,0.334029,0.665971
4,17839,2022,2021-10-20,WAS,TOR,98,83,120.0,-140.0,0,0.585499,0.414501,0.562044,0.437956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1318,19153,2022,2022-06-05,BOS,GSW,88,107,175.0,-200.0,1,0.521126,0.478874,0.647059,0.352941
1319,19154,2022,2022-06-08,GSW,BOS,100,116,135.0,-155.0,1,0.621509,0.378491,0.588212,0.411788
1320,19155,2022,2022-06-10,GSW,BOS,107,97,145.0,-165.0,0,0.641782,0.358218,0.604034,0.395966
1321,19156,2022,2022-06-13,BOS,GSW,94,104,145.0,-165.0,1,0.563516,0.436484,0.604034,0.395966
1322,19157,2022,2022-06-16,GSW,BOS,103,90,155.0,-175.0,0,0.582934,0.417066,0.618718,0.381282

In [150]:
h_kelly = []
a_kelly = []
for pred, price in data2022[["h_prob", "moneyline_home"]].iloc:
    h_kelly.append(Kelly_fraction(pred,price))
for pred, price in data2022[["a_prob", "moneyline_away"]].iloc:
    a_kelly.append(Kelly_fraction(pred,price)) 
data2022["home_kelly"] = h_kelly
data2022["away_kelly"] = a_kelly

In [151]:
data2022

,index,season,date,away,home,score_away,score_home,moneyline_away,moneyline_home,home_win,h_prob,a_prob,vegas_home_prob,vegas_away_prob,home_kelly,away_kelly
0,17835,2022,2021-10-19,BKN,MIL,104,127,105.0,-125.0,1,0.585499,0.414501,0.532468,0.467532,0.050000,0.000000
1,17836,2022,2021-10-19,GSW,LAL,121,114,140.0,-160.0,0,0.597031,0.402969,0.596273,0.403727,0.000000,0.000000
2,17837,2022,2021-10-20,IND,CHA,122,123,-125.0,105.0,1,0.585499,0.414501,0.467532,0.532468,0.050000,0.000000
3,17838,2022,2021-10-20,CHI,DET,94,88,-220.0,190.0,0,0.585499,0.414501,0.334029,0.665971,0.050000,0.000000
4,17839,2022,2021-10-20,WAS,TOR,98,83,120.0,-140.0,0,0.585499,0.414501,0.562044,0.437956,0.005197,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1318,19153,2022,2022-06-05,BOS,GSW,88,107,175.0,-200.0,1,0.521126,0.478874,0.647059,0.352941,0.000000,0.050000
1319,19154,2022,2022-06-08,GSW,BOS,100,116,135.0,-155.0,1,0.621509,0.378491,0.588212,0.411788,0.034847,0.000000
1320,19155,2022,2022-06-10,GSW,BOS,107,97,145.0,-165.0,0,0.641782,0.358218,0.604034,0.395966,0.050000,0.000000
1321,19156,2022,2022-06-13,BOS,GSW,94,104,145.0,-165.0,1,0.563516,0.436484,0.604034,0.395966,0.000000,0.047853
1322,19157,2022,2022-06-16,GSW,BOS,103,90,155.0,-175.0,0,0.582934,0.417066,0.618718,0.381282,0.000000,0.040980

In [152]:
def cash_multi(odds):
    if odds > 0:
        return (odds / 100)
    else:
        return (100/ abs(odds))

In [153]:
def simulation(h_kelly, a_kelly, h_win, h_odds, a_odds, cash = 100):
    if h_kelly == a_kelly:
        return 0
    elif h_kelly > a_kelly:
        if h_win:
            return h_kelly * cash * cash_multi(h_odds)
        else:
            return -h_kelly * cash
    else:
        if h_win:
            return -a_kelly * cash 
        else:
            return a_kelly * cash * cash_multi(a_odds)

In [154]:
money_made = []
for h_kelly, a_kelly, h_win, h_odds, a_odds in data2022[['home_kelly','away_kelly', 'home_win', 'moneyline_home', 'moneyline_away']].iloc:
    money_made.append(simulation(h_kelly, a_kelly, h_win, h_odds, a_odds))

In [155]:
data2022['money_made'] = money_made

In [156]:
data2022['money_made']

0       4.000000
1       0.000000
2       5.250000
3      -5.000000
4      -0.519683
          ...
1318   -5.000000
1319    2.248220
1320   -5.000000
1321   -4.785256
1322    6.351922
Name: money_made, Length: 1323, dtype: float64

In [157]:
data2022['money_made'].sum()

np.float64(-125.16149064684228)